name: 自动签到

on:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install build
      - name: Run
        env:
          STT_DOMAIN: ${{ secrets.STT_DOMAIN }}
          STT_USER_NAME: ${{ secrets.STT_USER_NAME }}
          STT_PASSWORD: ${{ secrets.STT_PASSWORD }}
          PMQZ_USER_NAME: ${{ secrets.PMQZ_USER_NAME }}
          PMQZ_PASSWORD: ${{ secrets.PMQZ_PASSWORD }}
          WSPM_USER_NAME: ${{ secrets.WSPM_USER_NAME }}
          WSPM_PASSWORD: ${{ secrets.WSPM_PASSWORD }}
          YNOTE_COOKIE: ${{ secrets.YNOTE_COOKIE }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          WEIXIN_UID: ${{ secrets.WEIXIN_UID }}
          WEIXIN_APP_TOKEN: ${{ secrets.WEIXIN_APP_TOKEN }}
        run: python ./youdaonote/note_checkin.py