name: 自动签到

on:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: "20 1 * * *"
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run-sttcloud
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
          WEIXIN_UID: ${{ secrets.WEIXIN_UID }}
          WEIXIN_APP_TOKEN: ${{ secrets.WEIXIN_APP_TOKEN }}
          PUSH_TYPE: ${{ secrets.PUSH_TYPE }}
          STT_DOMAIN: ${{ secrets.STT_DOMAIN }}
          STT_USER_NAME: ${{ secrets.STT_USER_NAME }}
          STT_PASSWORD: ${{ secrets.STT_PASSWORD }}
        run: python -m checkin.sttcloud
      - name: Run-Juejin
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
          WEIXIN_UID: ${{ secrets.WEIXIN_UID }}
          WEIXIN_APP_TOKEN: ${{ secrets.WEIXIN_APP_TOKEN }}
          PUSH_TYPE: ${{ secrets.PUSH_TYPE }}
          JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
          JUEJIN_A_BOGUS: ${{ secrets.JUEJIN_A_BOGUS }}
          JUEJIN_MS_TOKEN: ${{ secrets.JUEJIN_MS_TOKEN }}
        run: python -m checkin.juejin
